services:

  postgres:
    image: postgres:17.5-alpine
    container_name: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD?Variable not set}
      POSTGRES_USER: ${DATABASE_PASSWORD?Variable not set}
      POSTGRES_DB: ${DATABASE_NAME?Variable not set}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      # - postgres-db:/var/lib/postgresql/data
      - ./data:/var/lib/postgresql/data
    networks:
      - fastnet


  nginx:
    image: nginx:1.29.0
    container_name: nginx
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80"
    restart: unless-stopped
    volumes:
      - ./nginx/default:/etc/nginx/sites-available/default
    networks:
      - fastnet

networks:
  fastnet:

# volumes:
#   postgres-db:

