services:
  fastapi:
    build:
      target: prod
    env_file:
      - .env.prod
    environment:
      - ENVIRONMENT=production
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
  db:
    env_file:
      - .env.prod
