name: Build and Deploy Code

on: [ push, pull_request ]

jobs:
  build:
    environment:
      name: FastAPI-Testing
    env:
      POSTGRES_SERVER: ${{POSTGRES_SERVER}}
      POSTGRES_PORT: ${{POSTGRES_PORT}}
      POSTGRES_DB: ${{POSTGRES_DB}}
      POSTGRES_USER: ${{POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD}}
      SECRET_KEY: ${{SECRET_KEY}}
      ALGORITHM: ${{ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ACCESS_TOKEN_EXPIRE_MINUTES}}

    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v4

      - name: Install Python version 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install all python dependencies
        run: pip3 install -r requirements.txt

      - name: Test with Pytest
        run: |
          pip install pytest
          pytest