name: Build and Deploy Code

on: [ push, pull_request ]

jobs:
  build:
    environment:
      name: FastAPI-Testing
    env:
      #      POSTGRES_SERVER: ${{secrets.POSTGRES_SERVER}}
      #      POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
      #      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      #      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      #      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_SERVER: 127.0.0.1
      POSTGRES_PORT: 5454
      POSTGRES_DB: fastapi_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwod123
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    services:
      postgres:
        image: postgres:17.5-alpine
        ports:
          - 5454:5432
        env:
          POSTGRES_DB: fastapi_test
          POSTGRES_PASSWORD: password123
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test with Pytest
        run: pytest -v --disable-warnings tests/test_main.py
